tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
brew "bat"
brew "bzip2"
brew "composer"
brew "firebase-cli"
brew "gh"
brew "ghq"
brew "git"
brew "glib"
brew "python@3.10"
brew "googler"
brew "jq"
brew "krb5"
brew "mas"
brew "n"
brew "pandoc"
brew "peco"
brew "pnpm"
brew "pyenv"
brew "screen"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "heroku/brew/heroku"
cask "brave-browser"
cask "clipy"
cask "discord"
cask "docker"
cask "eul"
cask "figma"
cask "firefox"
cask "gifox"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "kindle"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "notion"
cask "numi"
cask "obsidian"
cask "onedrive"
cask "readdle-spark"
cask "slack"
cask "steam"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "zoom"
mas "BetterSnapTool", id: 417375580
mas "Focus", id: 777233759
mas "iMovie", id: 408981434
mas "InsomniaZ", id: 1447041581
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Remote Desktop", id: 1295203466
mas "Prime Video", id: 545519333
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835